### ISSUE TITLE
New conversation user list is only populated correctly the first time.

### ISSUE THREAD

**Issue by willwagner602** [TW1LL/TW1LL-Server#3]
I was able to narrow down the issue this far but not solve it:
1. The user clicks "+ New Conversation", script.js fires newConversations.  
2. newConversations creates "convFriendList" item
3. newConversations fires DOM.find("convFriendList") which find the correct element.
4. It passes this to updateList and the list is updated correctly.
5. When the user clicks to another area, that overwrites the existing "convFriendList"
6. User clicks "+ New Conversation" a subsequent time
7. newConversations creates "convFriendList" item again
8. newConversations fires DOM.find("convFriendList"), but this time it still finds the original "convFriendList" element. Confirmed by putting a timestamp on the element, it will always continue to find the original element until the page is fully refreshed.

**Comment by tfitz237** [comment]
So we need to clear the inner HTML of wherever the convfriendlist is being created, therefore removing it from the Dom so newConv can create a new one successfully

**Comment by tfitz237** [comment]
Or we make a dedicated convfriendlist in the DOM so newConv doesn't need to create a new one

**Comment by willwagner602** [comment]
Okay I messed around with it but wasn't able to get the first one working.  Not quite sure how to do the second one but not worrying about it for now.

**Comment by willwagner602** [comment]
Pretty sure something you committed yesterday fixed this.  I can add friends and see them come up in the new conversations list.
